# Generated by Django 4.2 on 2023-04-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DanielApp', '0002_alter_student_age_alter_student_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Position', models.CharField(max_length=50)),
                ('Office', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('StartDate', models.DateField()),
                ('Salary', models.IntegerField()),
            ],
        ),
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
    ]
